backend:
  name: git-gateway
  branch: master
media_folder: source/images/uploads
public_folder: /images/uploads
site_url: 'https://rm-frontend.ruhmesmeile.rocks'
display_url: 'https://rm-frontend.ruhmesmeile.rocks'
logo_url: 'https://rm-frontend.ruhmesmeile.rocks/images/ruhmesmeile-87496265.png'
locale: de
collections:
  - name: blog
    label: Blog
    folder: source/blog
    create: true
    slug: 'blog/{{slug}}'
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: blog
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: thumbnail
        widget: image
      - label: Rating (scale of 1-5)
        name: rating
        widget: number
      - label: Body
        name: body
        widget: markdown
  - name: pages
    label: Pages
    label_singular: Page
    description: Pages consisting of default content element
    folder: source
    create: true
    slug: '{{slug}}'
    fields:
      - label: Layout
        name: layout
        description: Layout to use
        widget: hidden
        default: default
      - label: Title
        name: title
        description: Title of the page
        widget: string
      - label: Heading
        name: heading
        description: Main headline of the page
        widget: string
      - label: Body
        name: body
        description: Bodytext for the page
        widget: markdown
      - label: Keyvisual
        name: keyvisual
        widget: object
        fields:
          - label: Small
            name: small
            widget: boolean
            default: false
            hint: Display smaller version
          - label: Background Color
            name: bg-color
            widget: string
            default: ''
            hint: Background HEX Color
          - label: Image (mobile)
            name: image-mobile
            widget: image
            default: dummy/64-27-l.png
            hint: Image for mobile verison
          - label: Image (tablet)
            name: image-tablet
            widget: image
            default: dummy/64-27-xl.png
            hint: Image for tablet version
          - label: Image (desktop)
            name: image-desktop
            widget: image
            default: dummy/64-27-xxxl.png
            hint: Image for desktop version
          - label: Box visible
            name: box
            widget: boolean
            default: true
            hint: Display box overlay
          - label: Box Alignment
            name: box-alignment
            widget: select
            default: keyvisual__content--center
            hint: Box alignment BEM class
            options:
              - label: Keyvisual center
                value: keyvisual__content--center
              - label: Content center
                value: visual-content--center
              - label: 'Left, content indent'
                value: visual-content--left visual-content--indent
              - label: 'Right, content indent'
                value: visual-content--right visual-content--indent
              - label: Right
                value: visual-content--right
              - label: Center Bottom
                value: visual-content--center visual-content--bottom
              - label: Center Top
                value: visual-content--center visual-content--top
          - label: Box style
            name: box-style
            widget: select
            default: ''
            hint: Box style BEM class
            options:
              - label: Light
                value: keyvisual__box--light
              - label: Text Dark
                value: keyvisual__box--transparent_text_dark
              - label: Transparent
                value: keyvisual__box--transparent
          - label: Box headline
            name: headline
            widget: string
            default: ''
            hint: Headline
          - label: Box text
            name: text
            widget: markdown
            default: ''
            hint: Bodytext
          - label: Link variant
            name: link-variant
            widget: select
            default: button--outline_inverted
            hint: Link variant BEM class
            options:
              - label: Inverted
                value: button--outline_inverted
              - label: Normal
                value: button--outline
          - label: Link text
            name: link-text
            widget: string
            default: ''
            hint: Link text
          - label: Link target
            name: link-target
            widget: string
            default: ''
            hint: Link target
  - name: settings
    description: General settings
    label: Settings
    label_singular: Setting
    files:
      - label: Navigation
        name: navigation
        file: source/settings/navigation.yml
        fields:
          - widget: object
            label: Main navigation
            name: main-nav
            description: Main navigation (sidebar or top)
            fields:
              - label: Links
                label_singular: Link
                name: links
                description: 1st level links
                widget: list
                fields:
                  - label: Label
                    name: label
                    description: Link text
                    widget: string
                  - label: Page
                    name: page
                    description: Link any page
                    widget: relation
                    collection: pages
                    searchFields:
                      - title
                    valueField: title
                    displayFields:
                      - title
                  - label: Open in new window
                    name: new-window
                    description: Should the link be opened in a new window?
                    widget: boolean
                    required: false
                  - label: Links
                    label_singular: Link
                    name: links
                    description: 2nd level links
                    widget: list
                    fields:
                      - label: Label
                        name: label
                        description: Link text
                        widget: string
                      - label: Path
                        name: path
                        description: Link any page
                        widget: relation
                        collection: pages
                        searchFields:
                          - title
                        valueField: title
                        displayFields:
                          - title
                      - label: Open in new window
                        name: new-window
                        description: Should the link be opened in a new window?
                        widget: boolean
                        required: false
