backend:
  name: git-gateway
  branch: master
media_folder: source/images/uploads
public_folder: /images/uploads
site_url: 'https://rm-frontend.ruhmesmeile.rocks'
display_url: 'https://rm-frontend.ruhmesmeile.rocks'
logo_url: 'https://rm-frontend.ruhmesmeile.rocks/images/ruhmesmeile-87496265.png'
locale: de
collections:
  - name: blog
    label: Blog
    folder: source/blog
    create: true
    slug: 'blog/{{slug}}'
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: blog
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: thumbnail
        widget: image
      - label: Rating (scale of 1-5)
        name: rating
        widget: number
      - label: Body
        name: body
        widget: markdown
  - name: pages
    label: Pages
    label_singular: Page
    description: Pages consisting of default content element
    folder: source
    create: true
    slug: '{{slug}}'
    fields:
      - label: Id
        name: Id
        description: Id
        widget: id
      - label: Layout
        name: layout
        description: Layout to use
        widget: hidden
        default: default
      - label: Keyvisual
        name: keyvisual
        widget: object
        fields:
          - label: Show
            name: show
            description: 'Choose wether to show the element, or not'
            widget: boolean
            default: false
          - label: Small
            name: small
            widget: boolean
            default: false
            hint: Display smaller version
          - label: Background Color
            name: bg-color
            widget: string
            default: ''
            hint: Background HEX Color
          - label: Image (mobile)
            name: image-mobile
            widget: image
            default: dummy/64-27-l.png
            hint: Image for mobile verison
          - label: Image (tablet)
            name: image-tablet
            widget: image
            default: dummy/64-27-xl.png
            hint: Image for tablet version
          - label: Image (desktop)
            name: image-desktop
            widget: image
            default: dummy/64-27-xxxl.png
            hint: Image for desktop version
          - label: Box visible
            name: box
            widget: boolean
            default: true
            hint: Display box overlay
          - label: Box Alignment
            name: box-alignment
            widget: select
            default: keyvisual__content--center
            hint: Box alignment BEM class
            options:
              - label: Left
                value: keyvisual__content--center
              - label: 'Left, content indent'
                value: visual-content--left visual-content--indent
              - label: Center
                value: visual-content--center
              - label: Center Bottom
                value: visual-content--center visual-content--bottom
              - label: Center Top
                value: visual-content--center visual-content--top
              - label: Right
                value: visual-content--right
              - label: 'Right, content indent'
                value: visual-content--right visual-content--indent
          - label: Box style
            name: box-style
            widget: select
            default: ''
            hint: Box style BEM class
            options:
              - label: Light
                value: keyvisual__box--light
              - label: Text Dark
                value: keyvisual__box--transparent_text_dark
              - label: Transparent
                value: keyvisual__box--transparent
          - label: Box headline
            name: headline
            widget: string
            default: ''
            hint: Headline
          - label: Box text
            name: text
            widget: markdown
            default: ''
            hint: Bodytext
          - label: Link variant
            name: link-variant
            widget: select
            default: button--outline_inverted
            hint: Link variant BEM class
            options:
              - label: Inverted
                value: button--outline_inverted
              - label: Normal
                value: button--outline
          - label: Link text
            name: link-text
            widget: string
            default: ''
            hint: Link text
          - label: Link target
            name: link-target
            widget: string
            default: ''
            hint: Link target
      - label: Heading
        name: heading
        description: Main headline of the page
        widget: string
      - label: Content
        name: content
        description: Content for the page
        widget: list
        types:
          - label: Teaser Box
            name: teaser-box
            widget: object
            fields:
              - label: Items
                name: items
                widget: list
                default: []
                hint: Items for teaser box
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: dummy/64-27-l.png
                    hint: Image for teaser box item
                  - label: Text
                    name: text
                    widget: markdown
                    default: ''
                    hint: Text for teaser box item
                  - label: Title
                    name: topic
                    widget: string
                    default: ''
                    hint: Title for teaser box item
                  - label: Link Button Text
                    name: link-button-text
                    widget: string
                    default: More
                    hint: Link Button Text for teaser box item
                  - label: Link target
                    name: href
                    widget: string
                    default: ''
                    hint: Link target
          - label: Textpic Intextleft
            name: textpic-intextleft
            widget: object
            fields:
              - label: Headline
                name: headline
                widget: object
                fields:
                  - label: Main Headline
                    name: mainheader
                    widget: string
                    default: ''
                    hint: Main Headline portion of Headline
                  - label: Sub Headline
                    name: subheader
                    widget: string
                    default: ''
                    hint: Sub Headline portion of Headline
              - label: Textpic
                name: textpic
                widget: object
                fields:
                  - label: Image
                    name: image
                    widget: image
                    default: dummy/64-27-l.png
                    hint: Image for Textpic
                  - label: Caption
                    name: caption
                    widget: string
                    default: ''
                    hint: Caption for Textpic
              - label: Content
                name: content
                widget: markdown
                default: ''
                hint: Bodytext
  - name: settings
    description: General settings
    label: Settings
    label_singular: Setting
    files:
      - label: Navigation
        name: navigation
        file: source/settings/navigation.yml
        fields:
          - widget: object
            label: Homepage
            name: homepage
            description: Page to initially display
            fields:
              - label: Label
                name: label
                description: Link text
                widget: string
              - label: Page
                name: page
                description: Link any page
                widget: relation
                collection: pages
                searchFields:
                  - title
                valueField: Id
                displayFields:
                  - title
          - widget: object
            label: Main navigation
            name: main-nav
            description: Main navigation (sidebar or top)
            fields:
              - label: Links
                label_singular: Link
                name: links
                description: 1st level links
                widget: list
                fields:
                  - label: Label
                    name: label
                    description: Link text
                    widget: string
                  - label: Page
                    name: page
                    description: Link any page
                    widget: relation
                    collection: pages
                    searchFields:
                      - title
                    valueField: Id
                    displayFields:
                      - title
                  - label: Links
                    label_singular: Link
                    name: links
                    description: 2nd level links
                    widget: list
                    fields:
                      - label: Label
                        name: label
                        description: Link text
                        widget: string
                      - label: Page
                        name: page
                        description: Link any page
                        widget: relation
                        collection: pages
                        searchFields:
                          - title
                        valueField: Id
                        displayFields:
                          - title
                      - label: Links
                        label_singular: Link
                        name: links
                        description: 3rd level links
                        widget: list
                        fields:
                          - label: Label
                            name: label
                            description: Link text
                            widget: string
                          - label: Page
                            name: page
                            description: Link any page
                            widget: relation
                            collection: pages
                            searchFields:
                              - title
                            valueField: Id
                            displayFields:
                              - title
