backend:
  name: git-gateway
  branch: master
media_folder: source/images/uploads
public_folder: /images/uploads
site_url: 'https://rm-frontend.ruhmesmeile.rocks'
display_url: 'https://rm-frontend.ruhmesmeile.rocks'
logo_url: 'https://rm-frontend.ruhmesmeile.rocks/images/ruhmesmeile-87496265.png'
locale: de
collections:
  - name: blog
    label: Blog
    folder: source/blog
    create: true
    slug: 'blog/{{slug}}'
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: blog
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: thumbnail
        widget: image
      - label: Rating (scale of 1-5)
        name: rating
        widget: number
      - label: Body
        name: body
        widget: markdown
  - name: pages
    label: Pages
    folder: source
    create: true
    slug: '{{slug}}'
    fields:
      - label: Layout
        name: layout
        widget: hidden
        default: default
      - label: Title
        name: title
        widget: string
      - label: Heading
        name: heading
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Keyvisual
        name: keyvisual
        widget: object
        fields:
          - label: Small
            name: small
            widget: boolean
            default: false
          - label: Bg-color
            name: bg-color
            widget: string
            default: ''
          - label: Image-mobile
            name: image-mobile
            widget: string
            default: dummy/64-27-l.png
          - label: Image-tablet
            name: image-tablet
            widget: string
            default: dummy/64-27-xl.png
          - label: Image-desktop
            name: image-desktop
            widget: string
            default: dummy/64-27-xxxl.png
          - label: Box
            name: box
            widget: boolean
            default: true
          - label: Box-alignment
            name: box-alignment
            widget: select
            default: keyvisual__content--center
            options:
              - keyvisual__content--center
              - visual-content--center
              - visual-content--left visual-content--indent
              - visual-content--right visual-content--indent
              - visual-content--right
              - visual-content--center visual-content--bottom
              - visual-content--center visual-content--top
          - label: Box-style
            name: box-style
            widget: select
            default: ''
            options:
              - keyvisual__box--light
              - keyvisual__box--transparent_text_dark
              - keyvisual__box--transparent
          - label: Headline
            name: headline
            widget: string
            default: ''
          - label: Text
            name: text
            widget: boolean
            default: ''
          - label: Link-variant
            name: link-variant
            widget: select
            default: button--outline_inverted
            options:
              - button--outline_inverted
              - button--outline
          - label: Link-text
            name: link-text
            widget: string
            default: ''
